---
# tasks file for roles/delete_network

- name: delete network
  os_network:
    auth:
      auth_url: '{{ auth_url }}'
      username: '{{ username }}'
      password: '{{ password }}'
      project_name: '{{ project_name }}'
    name: '{{ network_name }}'
    state: absent
