---
# tasks file for delete boot_volume

- name: delete boot volume
  os_volume:
    auth:
      auth_url: '{{ auth_url }}'
      username: '{{ username }}'
      password: '{{ password }}'
      project_name: '{{ project_name }}'
    state: absent
    display_name: '{{ boot_display_name }}'
    timeout: 300
